version: "3"

vars:
  CERTS_DIR: "{{.ROOT_DIR}}/certs"
  CERTBOT_IMAGE: certbot/certbot:v2.6.0
  STATIC_ROOT: "{{.ROOT_DIR}}/htdocs"
  STATIC_PATH: .well-known
  NGINX_CONTAINER_NAME: gaiax_nginx
  NGINX_IMAGE_TAG: 1.23
  FILENAME_X5U: x5u.pem
  FILENAME_DID: did.json
  FILENAME_VP: vp.json
  FILENAME_LRN: lrn.json
  FILENAME_TC: tsandcs.json
  FILENAME_PARTICIPANT: participant.json

env:
  PATH_CERTIFICATE: "{{.CERTS_DIR}}/cert.pem"
  PATH_PRIVATE_KEY: "{{.CERTS_DIR}}/privkey.pem"
  BASE_URL: "https://{{.CERTBOT_DOMAIN}}/{{.STATIC_PATH}}"
  WEBSERVER_DIR: "{{.STATIC_ROOT}}/{{.STATIC_PATH}}"
  DID_WEB_ID: 
    sh: if [[ "{{.STATIC_PATH}}" == ".well-known" ]]; then echo "did:web:{{.CERTBOT_DOMAIN}}"; else echo "did:web:{{.CERTBOT_DOMAIN}}:{{.STATIC_PATH}}"; fi
  FILENAME_X5U: "{{.FILENAME_X5U}}"
  FILENAME_DID: "{{.FILENAME_DID}}"
  FILENAME_VP: "{{.FILENAME_VP}}"
  FILENAME_LRN: "{{.FILENAME_LRN}}"
  FILENAME_TC: "{{.FILENAME_TC}}"
  FILENAME_PARTICIPANT: "{{.FILENAME_PARTICIPANT}}"

# Create a dotenv .env file in the root folder
# to override the default values defined in .env.default
dotenv: [.env, .env.default]

tasks:
  check-sudo:
    desc: Check if the user is root
    cmds:
      - >
        if [ "$(id -u)" != "0" ]; then
          echo "This task must be run as root. Please use sudo."
          exit 1
        fi

  chown-certs:
    desc: Change the owner of the certs folder to the current user
    deps:
      - check-sudo
    cmds:
      - chown -R $(logname):$(id -gn $(logname)) {{.CERTS_DIR}}

  get-certs:
    desc: Get the SSL certificates from Let's Encrypt
    deps:
      - check-sudo
    cmds:
      - >
        docker run -it --rm -p 80:80 
        -v "/etc/letsencrypt:/etc/letsencrypt" 
        -v "/var/lib/letsencrypt:/var/lib/letsencrypt" 
        {{.CERTBOT_IMAGE}}
        --preferred-chain="ISRG Root X1" 
        certonly 
        --standalone -n --agree-tos --key-type rsa --email {{.CERTBOT_EMAIL}} -d {{.CERTBOT_DOMAIN}}
      - mkdir -p {{.CERTS_DIR}}
      - cp -Lr /etc/letsencrypt/live/{{.CERTBOT_DOMAIN}}/* {{.CERTS_DIR}}
      - task: chown-certs

  build-did:
    desc: Build and write the DID and x.509 certificate chain
    cmds:
      - mkdir -p {{.STATIC_ROOT}}/{{.STATIC_PATH}}
      - npm run build-did
      - cp {{.CERTS_DIR}}/fullchain.pem {{.STATIC_ROOT}}/{{.STATIC_PATH}}/{{.FILENAME_X5U}}
      # We need to add the root certificate to the chain for the Compliance request to work
      # Note that we indicated that we want to use the "ISRG Root X1" root using the preferred-chain option
      - wget https://letsencrypt.org/certs/isrgrootx1.pem -O {{.CERTS_DIR}}/isrgrootx1.pem
      - cat {{.CERTS_DIR}}/isrgrootx1.pem >> {{.STATIC_ROOT}}/{{.STATIC_PATH}}/{{.FILENAME_X5U}}
    preconditions:
      - sh: test -f {{.CERTS_DIR}}/fullchain.pem
        msg: Please run the task to get the SSL certificates first

  start-webserver:
    desc: Build the DID and x.509 certificate chain and then start the NGINX web server
    cmds:
      - task: build-did
      - cmd: docker stop {{.NGINX_CONTAINER_NAME}}
        ignore_error: true
      - cmd: docker rm -f {{.NGINX_CONTAINER_NAME}}
        ignore_error: true
      - > 
        docker run -d -p 443:443 
        --restart unless-stopped 
        --name {{.NGINX_CONTAINER_NAME}} 
        -v {{.ROOT_DIR}}/ssl.conf:/etc/nginx/conf.d/ssl.conf 
        -v {{.CERTS_DIR}}/privkey.pem:/etc/nginx/certs/key.pem 
        -v {{.CERTS_DIR}}/fullchain.pem:/etc/nginx/certs/cert.pem 
        -v {{.STATIC_ROOT}}:/usr/share/nginx/html/ 
        nginx:{{.NGINX_IMAGE_TAG}}

  request-compliance:
    desc: Call the Compliance API to get integrity proofs and expose the resulting Verifiable Presentation
    deps:
      - start-webserver
    cmds:
      - npm run validate-compliance
